os: linux
dist: focal
language: python
python: 3.8
cache: pip
before_install: pip install --upgrade pip setuptools six
jobs:
  include:
    - name: Build
      install: pip install pytest-cov -r requirements.txt
      script:
        - pytest --doctest-modules --ignore=project_euler/ --cov-report=term-missing:skip-covered --cov=. .
after_success:
  - scripts/build_directory_md.py 2>&1 | tee DIRECTORY.md
notifications:
  webhooks: https://www.travisbuddy.com/
  on_success: never
