os: linux
dist: focal
language: python
python: 3.9
cache: pip
before_install: pip install --upgrade pip setuptools six wheel --only-binary=numpy --only-binary=scipy
jobs:
  include:
    - script: pip install scipy
    - script: pip install statsmodels
    - script: pip install tensorflow
    - name: Build
      install: pip install pytest-cov -r requirements.txt
      script:
        - pytest --doctest-modules --ignore=project_euler/ --cov-report=term-missing:skip-covered --cov=. .
  allow_failures:
    - script: pip install scipy
    - script: pip install statsmodels
    - script: pip install tensorflow    
after_success:
  - scripts/build_directory_md.py 2>&1 | tee DIRECTORY.md
notifications:
  webhooks: https://www.travisbuddy.com/
  on_success: never
