os: linux
dist: focal
language: python
python: 3.9
cache: pip
before_install: pip install --upgrade pip setuptools six wheel
jobs:
  include:
    - install: true
      script: pip install --only-binary=scipy scipy
    - install: true
      script: pip install --only-binary=scipy statsmodels
    - install: true
      script: pip install --only-binary=scipy tensorflow
    - name: Build
      install: pip install --only-binary=numpy --only-binary=scipy pytest-cov -r requirements.txt
      script:
        - pytest --doctest-modules --ignore=project_euler/ --cov-report=term-missing:skip-covered --cov=. .
  allow_failures:
    - install: true   
after_success:
  - scripts/build_directory_md.py 2>&1 | tee DIRECTORY.md
notifications:
  webhooks: https://www.travisbuddy.com/
  on_success: never
