language: python
dist: xenial  # required for Python >= 3.7
python: 3.7
cache: pip
before_install: pip install --upgrade pip setuptools
install: pip install -r requirements.txt
before_script:
  - black --check . || true
  - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
script:
  - mypy --ignore-missing-imports .
  - pytest . --doctest-modules
      --ignore=data_structures/stacks/balanced_parentheses.py
      --ignore=data_structures/stacks/infix_to_postfix_conversion.py
      --ignore=machine_learning/linear_regression.py
      --ignore=machine_learning/perceptron.py
      --ignore=machine_learning/random_forest_classification/random_forest_classification.py
      --ignore=machine_learning/random_forest_regression/random_forest_regression.py
      --ignore=maths/abs_min.py
      --ignore=maths/binary_exponentiation.py
      --ignore=maths/lucas_series.py
      --ignore=maths/sieve_of_eratosthenes.py
      --ignore=virtualenv  # do not test our dependencies
after_success:
  - python scripts/build_directory_md.py
  - cat DIRECTORY.md
