os: linux
dist: focal
language: python
python: 3.8
cache: pip
before_install: pip install --upgrade pip setuptools six
install: pip install -r requirements.txt
before_script:
  - black --check . || true
  - flake8 . --count --select=E101,E5,E722,E9,F4,F63,F7,F82,W191 --max-complexity=25 --max-line-length=127 --show-source --statistics
  - flake8 . --count --exit-zero --max-line-length=127 --statistics
script:
  - scripts/validate_filenames.py  # no uppercase, no spaces, in a directory
  - mypy --ignore-missing-imports .
  - pytest --doctest-modules --cov-report=term-missing:skip-covered --cov=. .
after_success:
  - scripts/build_directory_md.py 2>&1 | tee DIRECTORY.md
