name: "build"

on:
  pull_request:
  schedule:
    - cron: "0 0 * * *" # Run everyday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get update && sudo apt-get install -y \
          libtiff5-dev libjpeg8-dev libopenjp2-7-dev \
          zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev \
          tcl8.6-dev tk8.6-dev python3-tk libharfbuzz-dev \
          libfribidi-dev libxcb1-dev libxml2-dev libxslt-dev \
          libhdf5-dev libopenblas-dev

      - uses: actions/checkout@v5

      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock

      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
          allow-prereleases: true

      - run: uv sync --group=test

      - name: Run tests
        run: |
          uv run pytest \
          --ignore=computer_vision/cnn_classification.py \
          --ignore=docs/conf.py \
          --ignore=dynamic_programming/k_means_clustering_tensorflow.py \
          --ignore=machine_learning/lstm/lstm_prediction.py \
          --ignore=neural_network/input_data.py \
          --ignore=project_euler/ \
          --ignore=quantum/q_fourier_transform.py \
          --ignore=scripts/validate_solutions.py \
          --ignore=web_programming/current_stock_price.py \
          --ignore=web_programming/fetch_anime_and_play.py \
          --cov-report=term-missing:skip-covered \
          --cov=. .

      - if: ${{ success() }}
        run: scripts/build_directory_md.py 2>&1 | tee DIRECTORY.md
