# GitHub Action to automate the identification of common misspellings in text files
# https://github.com/codespell-project/codespell
name: codespell
on: [push, pull_request]
jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install codespell
      - run: |
          SKIP="./.*,./other/dictionary.txt,./other/words,./project_euler/problem_022/p022_names.txt"
          codespell --ignore-words-list=ans,fo,followings,hist,iff,secant,som,tim --skip=$SKIP --quiet-level=2
      - name: Codespell comment
        if: ${{ failure() }}
        uses: plettich/python_codespell_action@master
